%YAML:1.0
---
Markers:
  - Points:
    -
      freq: 8000
      x: 0.1
      y: 0.0
      z: 0.0
    -
      freq: 8200
      x: 0.1300
      y: 0.0
      z: 0.0
    -
      freq: 8400
      x: 0.13
      y: 0.03
      z: 0.0
    -
      freq: 8600
      x: 0.1
      y: 0.03
      z: 0.0

    - 
      freq: 10000
      x: 0.0
      y: 0.0
      z: 0.0
    - 
      freq: 10200
      x: 0.03
      y: 0.0
      z: 0.0
    - 
      freq: 10400
      x: 0.03
      y: 0.03
      z: 0.0
    - 
      freq: 10600
      x: 0.0
      y: 0.03
      z: 0.0
    ID: 2